"""Recreate sync with CNIC and profile fields

Revision ID: 3a9162fb8501
Revises: 
Create Date: 2025-10-25 12:15:41.779688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a9162fb8501'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('profile_locked', sa.BOOLEAN(), nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('username', sa.VARCHAR(length=64), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=False),
    sa.Column('shift', sa.VARCHAR(length=20), nullable=True),
    sa.Column('role', sa.VARCHAR(length=20), nullable=False),
    sa.Column('company_id', sa.INTEGER(), nullable=True),
    sa.Column('salary', sa.FLOAT(), nullable=True),
    sa.Column('is_active_db', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('travel_allowance_eligible', sa.BOOLEAN(), nullable=True),
    sa.Column('travel_allowance_amount', sa.INTEGER(), nullable=True),
    sa.Column('father_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('current_address', sa.VARCHAR(length=255), nullable=False),
    sa.Column('permanent_address', sa.VARCHAR(length=255), nullable=False),
    sa.Column('contact_number', sa.VARCHAR(length=20), nullable=False),
    sa.Column('emergency_contact', sa.VARCHAR(length=20), nullable=False),
    sa.Column('whatsapp_number', sa.VARCHAR(length=20), nullable=False),
    sa.Column('blood_group', sa.VARCHAR(length=10), nullable=False),
    sa.Column('profile_picture', sa.VARCHAR(length=255), nullable=False),
    sa.Column('cnic_front', sa.VARCHAR(length=255), nullable=False),
    sa.Column('cnic_back', sa.VARCHAR(length=255), nullable=False),
    sa.Column('guardian_cnic_front', sa.VARCHAR(length=255), nullable=False),
    sa.Column('guardian_cnic_back', sa.VARCHAR(length=255), nullable=False),
    sa.Column('cnic', sa.VARCHAR(length=20), nullable=False),
    sa.Column('resume_path', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
