"""add broadcasts and broadcast_seen tables

Revision ID: 7ae04c9bb0b2
Revises: adb23b08696c
Create Date: 2025-10-26 11:22:27.045553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ae04c9bb0b2'
down_revision = 'adb23b08696c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('broadcasts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=200), nullable=True))
        batch_op.alter_column('target',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=32),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('broadcasts', schema=None) as batch_op:
        batch_op.alter_column('target',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('title')

    # ### end Alembic commands ###
