"""Fix penalty and clearance relationships clean

Revision ID: 98426c47421a
Revises: df255194ce77
Create Date: 2025-11-03 12:17:37.792787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98426c47421a'
down_revision = 'df255194ce77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_broadcast_seen')
    with op.batch_alter_table('broadcast_seen', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'broadcasts', ['broadcast_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('clearances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marked_by', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['marked_by'], ['id'])

    with op.batch_alter_table('penalties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marked_by', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['marked_by'], ['id'])
        batch_op.drop_column('added_by_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('penalties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('added_by_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['added_by_id'], ['id'])
        batch_op.drop_column('marked_by')

    with op.batch_alter_table('clearances', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('marked_by')

    with op.batch_alter_table('broadcast_seen', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'broadcasts', ['broadcast_id'], ['id'])
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    op.create_table('_alembic_tmp_broadcast_seen',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('broadcast_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('seen_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['broadcast_id'], ['broadcasts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broadcast_id', 'user_id', name=op.f('uq_broadcast_user_seen'))
    )
    # ### end Alembic commands ###
