"""add CNIC and father/resume fields to User

Revision ID: adb23b08696c
Revises: 3a9162fb8501
Create Date: 2025-10-25 12:17:26.191469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adb23b08696c'
down_revision = '3a9162fb8501'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cnic', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('resume_path', sa.String(length=255), nullable=True))
        batch_op.drop_column('cv_resume_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cv_resume_path', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('resume_path')
        batch_op.drop_column('cnic')

    # ### end Alembic commands ###
